### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "hansh1ng11111@123.com",
  "password": "12345336"
  
}

### Create a new user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "hansh1ng11111@123.com",
  "password": "12345336"
}


### Signout
POST http://localhost:3000/auth/signout


### Create a new user
GET  http://localhost:3000/auth/whoami

### Find a particular user
GET http://localhost:3000/auth/2


### Find all users with email
Get http://localhost:3000/auth?email=hanshua11ng@123.com


### Delete a user given the id
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "aaa@aaa.com"
}


### Set a color
GET http://localhost:3000/auth/colors/asdfdsafsda

### Get a color
GET http://localhost:3000/auth/colors